//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataServiceDemo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsite
    {
        public int sID { get; set; }
        public string sName { get; set; }
        public string sDB { get; set; }
        public string sLetter { get; set; }
    }
}
