//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataServiceDemo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluaresult
    {
        public tbluaresult()
        {
            this.tbluaresultdetails = new HashSet<tbluaresultdetail>();
        }
    
        public int uarID { get; set; }
        public int uarLngCltID { get; set; }
        public int uarSchedID { get; set; }
        public System.DateTime uarDropDt { get; set; }
        public System.DateTime uarResultDt { get; set; }
        public string uarCreatedBy { get; set; }
        public System.DateTime uarCreatedDt { get; set; }
    
        public virtual ICollection<tbluaresultdetail> tbluaresultdetails { get; set; }
    }
}
