//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataServiceDemo.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class tbluaresultdetail
    {
        public int uardID { get; set; }
        public int uardRecID { get; set; }
        public string uardResult { get; set; }
        public bool uardRX { get; set; }
        public string uaDetail { get; set; }

        public virtual tbluaresult tbluaresult { get; set; }
    }
}
