//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataServiceDemo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public int Uskey { get; set; }
        public string usrName { get; set; }
        public string usrFName { get; set; }
        public string usrLName { get; set; }
        public bool usrACTIVE { get; set; }
    }
}
